/*
 * @Descripttion:
 * @version:
 * @Author: 程
 * @Date: 2025-08-30 14:16:39
 * @LastEditors: 程
 * @LastEditTime: 2026-03-26 14:37:11
 */
import { ref } from 'vue';
const newToolItems: any = ref({
  frame: {
    text: '前端框架 - 文档',
    isExpand: true,
    items: [
      { id: 1, text: 'Vue', introduction: '渐进式 JavaScript 框架', url: 'https://vuejs.org/' },
      { id: 2, text: 'React', introduction: '用于构建用户界面的 JavaScript 库', url: 'https://react.docschina.org/' },
      { id: 3, text: 'React-docs', introduction: '小满react讲解文档很不错', url: 'https://message163.github.io/react-docs/' },
      { id: 4, text: 'Angular', introduction: '现代 Web 开发平台', url: 'https://angular.cn/' },
      { id: 5, text: 'uni-app', introduction: '是一个使用 Vue.js 开发所有前端应用的框架', url: 'https://uniapp.dcloud.net.cn/component/' },
      { id: 6, text: 'WeChat', introduction: '微信小程序是一种全新的连接用户与服务的方式', url: 'https://developers.weixin.qq.com/miniprogram/dev/component/' },
      { id: 7, text: 'Electron', introduction: '使用 Vue 构建桌面 应用程序的框架', url: 'https://electronjs.p2hp.com/docs/latest/index.html' },
    ],
  },
  webUi: {
    text: '前端Web UI库 - PC',
    isExpand: true,
    items: [
      { id: 1, text: 'Element-ui', introduction: '基于 Vue 2.0 的桌面端组件库', url: 'https://element.eleme.cn/#/zh-CN' },
      { id: 2, text: 'Element-plus', introduction: '基于 Vue 3，面向设计师和开发者的组件库', url: 'https://element-plus.org' },
      { id: 3, text: 'Ant Design Vue', introduction: 'Ant Design Vue 版本', url: 'https://www.antdv.com/components/overview-cn' },
      { id: 3, text: 'Ant Design', introduction: '助力设计开发者更灵活地搭建出更美的产品', url: 'https://ant.design/index-cn' },
      { id: 4, text: 'Naive Ui', introduction: '一个 Vue 3 组件库,使用 TypeScript，快有点意思', url: 'https://www.naiveui.com/zh-CN/os-theme' },
      { id: 5, text: 'Arco Design', introduction: '字节跳动产品设计系统，支持React和Vue双版本', url: 'https://arco.design/' },
      { id: 6, text: 'iDux', introduction: 'Vue3.x 的 UI 组件库，完全使用 TypeScript 开发', url: 'https://idux.site/' },
      { id: 7, text: 'Prime Vue', introduction: '易于使用、多功能、高性能的 Vue UI 组件库', url: 'https://www.primefaces.org/primevue/' },
      { id: 8, text: 'Dev UI', introduction: '华为基于 Vue3 和 DevUI 设计的 UI 组件', url: 'https://vue-devui.github.io/' },
      { id: 9, text: 'Headless UI', introduction: '完全无样式与 Tailwind CSS完美集成。', url: 'https://headlessui.com/' },
      { id: 10, text: 'View Design', introduction: '基于 Vue.js 3 的企业级 UI 组件库和前端解决方案', url: 'https://www.iviewui.com/' },
      { id: 11, text: 'Layui', introduction: '开源模块化前端 UI 框架', url: 'http://layui.winxapp.cn/' },
      { id: 12, text: 'Taro', introduction: 'Taro 是一个开放式跨端跨框架解决方案', url: 'https://taro-docs.jd.com/docs/' },
      { id: 4, text: 'Bootstrap', introduction: '简洁、直观、强悍的前端开发框架', url: 'https://www.bootcss.com/' },
      { id: 45, text: 'Ant-design-x', introduction: 'AI 体验新秩序插件,快速搭建AI聊天组件', url: 'https://ant-design-x.antgroup.com/index-cn' },
    ],
  },
  mobileUi: {
    text: '前端Web UI库 - 移动',
    isExpand: true,
    items: [
      { id: 1, text: 'Vant', introduction: '轻量、可靠的移动端 Vue 组件库', url: 'https://vant-ui.github.io/vant/#/zh-CN' },
      { id: 2, text: 'Nut UI', introduction: '京东风格的移动端Vue组件库,适合移动端电商使用', url: 'https://nutui.jd.com/#/' },
      { id: 3, text: 'VARLET', introduction: 'Material 风格移动端组件库 ，文档非常齐全', url: 'https://varlet.gitee.io/varlet-ui/#/zh-CN/index' },
      { id: 4, text: 'NutUI Bingo', introduction: '京东NutUI的抽奖组件库,营销活动和小游戏场景。', url: 'https://nutui.jd.com/bingo/#/' },
      { id: 5, text: 'Uview', introduction: '全面兼容nvue的uni-app生态框架', url: 'https://www.uviewui.com/' },
      { id: 6, text: 'Uview-plus', introduction: 'uviewPlus是基于uView修改的vue3版本', url: 'https://uiadmin.net/uview-plus/components/intro.html' },
      { id: 11, text: 'Uview-pro', introduction: 'uviewPro是基于uView修改的vue3版本', url: 'https://www.anyup.cn/docs/' },
      { id: 7, text: 'uv-ui/类似uview-plus', introduction: 'uviewPlus是基于uView2修改的vue3版本', url: 'https://www.uvui.cn/' },
      { id: 8, text: 'Taro UI', introduction: '一套基于 Taro 框架开发的多端 UI 组件库', url: 'https://taro-ui.jd.com/#/' },
      { id: 9, text: 'Wot Design Uni', introduction: '高颜值、轻量化的uni-app组件库', url: 'https://wot-design-uni.pages.dev/' },
      { id: 10, text: 'Cool Unix', introduction: 'uvue组件库、多语言、深色模式、Ai编码', url: 'https://unix.cool-js.com/' },
      { id: 11, text: 'tdesign', introduction: 'TDesign 微信小程序组件库。', url: 'https://tdesign.tencent.com/miniprogram/getting-started' },
    ],
  },
  visual: {
    text: '前端可视化',
    isExpand: false,
    items: [
      { id: 1, text: 'Echarts', introduction: 'Echarts', url: 'https://echarts.apache.org/zh/index.html' },
      { id: 1, text: 'PP Chart', introduction: '前端Echarts样式大全,前端必备', url: 'http://ppchart.com/#/' },
      { id: 2, text: 'Isqqw Chart', introduction: '前端Echarts样式大全,前端必备1', url: 'https://www.isqqw.com/#/homepage' },
      { id: 13, text: 'MCChanrt', introduction: '前端Echarts样式大全,前端必备2', url: 'https://echarts.zhangmuchen.top/#/index' },
      { id: 4, text: 'Echarts社区', introduction: '前端Echarts样式大全,前端必备3', url: 'https://www.makeapie.cn/echarts_category/series-map' },
      { id: 5, text: 'Madeapie', introduction: '前端Echarts样式大全,前端必备4', url: 'https://madeapie.com/#/' },
      { id: 6, text: 'DatavGeoAtlas', introduction: '地区数据可视化数据下载平台', url: 'http://datav.aliyun.com/portal/school/atlas/area_selector' },
      { id: 7, text: 'LogicFlow', introduction: '由滴滴体验平台技术研发的一款流程图编辑框架', url: 'http://logic-flow.org/' },
      { id: 8, text: 'Vue ECharts', introduction: '百度ECharts 的 Vue.js 组件', url: 'https://vue-echarts.dev/' },
      { id: 9, text: 'Feng Map', introduction: '室内3D图渲染插件', url: 'https://cloud.fengmap.com' },
      { id: 10, text: 'U charts 秋云', introduction: 'uniapp的图表工具', url: 'https://www.ucharts.cn/v2/#/' },
      { id: 11, text: 'Cola-Designer', introduction: '基于VUE2 拖拽 + 配置方式生成数据大屏', url: 'https://gitee.com/colaiven/cola-designer?url=eflyos.zip#https://gitee.com/link?target=http%3A%2F%2Fcolaiven.github.io%2Fcola-designer%2F%23%2Fdesign' },
      { id: 12, text: 'Nexthuman', introduction: '领先的数字生命引擎技术供应商/数字人', url: 'https://nexthuman.cn/wiki/home' },
      { id: 12, text: 'Visactor', introduction: '可视化图表库', url: 'https://www.visactor.io/vchart/example' },
      { id: 12, text: 'Photo-sphere-viewer', introduction: '用于显示 360° 全景图的 JavaScript 库', url: 'https://photo-sphere-viewer.js.org/' },
    ],
  },
  plugin: {
    text: '前端插件',
    isExpand: false,
    items: [
      { id: 1, text: 'Vue 插件库', introduction: 'Vue 插件库合集/大全/搜索', url: 'https://www.vue365.cn/' },
      { id: 2, text: 'Swiper', introduction: '开源、免费、强大的触摸滑动插件', url: 'https://www.swiper.com.cn/' },
      { id: 3, text: 'Animate', introduction: '超级简单的动画插件', url: 'https://animate.style/' },
      { id: 4, text: 'Tailwindcss', introduction: '无需离开您的HTML，即可快速建立现代网站。', url: 'https://www.tailwindcss.cn/' },
      { id: 5, text: 'Threejs', introduction: 'Three.js是一款WebGL三维引擎', url: 'https://threejs.org/' },
      { id: 2, text: 'TypeScript', introduction: 'TypeScript入门教程', url: 'https://roadmap.sh/roadmaps' },
      { id: 3, text: 'ThreeJs', introduction: 'ThreeJs入门教程', url: 'http://www.yanhuangxueyuan.com/' },
      { id: 3, text: 'ThreeJsFree模型', introduction: 'ThreeJs免费模型', url: 'https://www.blendswap.com/' },
      { id: 3, text: 'view3DGLB', introduction: '在线查看 3D GLB 文件', url: 'https://imagetostl.com/cn/view-glb-online#convert' },
      { id: 6, text: 'TypeScript', introduction: 'TypeScript是JavaScript类型的超集。', url: 'https://www.tslang.cn/index.html' },
      { id: 7, text: 'Vxetable', introduction: '一个基于 vue 的 PC 端复杂表格组件', url: 'https://vxetable.cn/#/table/start/install' },
      { id: 8, text: 'Vue3VideoPlay', introduction: '适用于 Vue3 的hls.js播放器组件', url: 'https://codelife.cc/vue3-video-play/' },
      { id: 9, text: 'Muiplayer', introduction: '一个优秀的HTML5监控视频播放器框架', url: 'https://muiplayer.js.org/' },
      { id: 9, text: 'EasyPlayer', introduction: 'H5视频直播/视频点播播放器', url: 'https://www.npmjs.com/package/@easydarwin/easyplayer' },
      { id: 10, text: 'Vue3SeamlessScroll', introduction: '一个基于 vue3 的滚动列表组件', url: 'https://github.com/xfy520/vue3-seamless-scroll' },
      { id: 11, text: 'Vue2SeamlessScroll', introduction: '一个基于 vue2 的滚动列表组件', url: 'https://chenxuan1993.gitee.io/component-document/index_prod#/component/seamless-others' },
      { id: 12, text: 'V3Directives', introduction: '一个Vue3自定义指令库合集', url: 'https://github.com/QishuangWang/v3-directives' },
      { id: 13, text: 'Lodash', introduction: 'Lodash 是一个高性能的 JavaScript 实用工具库。', url: 'https://www.lodashjs.com/' },
      { id: 14, text: 'Json2ts', introduction: 'Typescript快捷类型转换工具', url: 'https://tooltt.com/json2typescript/' },
      { id: 14, text: 'Json2ts', introduction: 'Typescript快捷类型转换工具-1', url: 'https://1json.zxlee.cn/' },
      { id: 14, text: 'Json2ts', introduction: 'Typescript快捷类型转换工具-2(整体转换)', url: 'https://app.quicktype.io/#l=ts' },
      { id: 15, text: 'Colorhunt', introduction: '一个色彩搭配大全网站', url: 'https://colorhunt.co/' },
      { id: 15, text: 'ColorGenerator', introduction: '一个色彩搭配大全网站', url: 'https://kigen.design/color' },
      { id: 16, text: 'Carbon', introduction: '一个代码截图网站', url: 'https://carbon.now.sh/' },
      { id: 17, text: 'UniAppDcloud', introduction: '一个uniapp的插件市场大全', url: 'https://ext.dcloud.net.cn/' },
      { id: 18, text: 'Regulex', introduction: 'JavaScript 正则表达式可视化工具', url: 'https://jex.im/regulex/#!flags=&re=%5E(a%7Cb)*%3F%24' },
      { id: 18, text: 'Regulex', introduction: '常用正则大全', url: 'https://any-rule.vercel.app/' },
      { id: 19, text: 'SortableJS', introduction: '功能强大的JavaScript 拖拽库', url: 'http://www.sortablejs.com/index.html' },
      { id: 39, text: 'Vue.Draggable', introduction: 'vue2/3拖拽组件', url: 'https://github.com/SortableJS/Vue.Draggable' },
      { id: 20, text: 'SnippetGenerator', introduction: '一个VsCode代码片段一键生成网站', url: 'https://snippet-generator.app/?description=&tabtrigger=&snippet=&mode=vscode' },
      { id: 21, text: 'GridGenerator', introduction: '一个Grid布局代码生成网站', url: 'https://cssgrid-generator.netlify.app/' },
      { id: 22, text: 'Codelf', introduction: '变量名称生成大全网站', url: 'https://unbug.github.io/codelf/' },
      { id: 23, text: 'DayJs', introduction: 'Day.js 是一个轻量的处理时间和日期的 JS 库', url: 'https://dayjs.gitee.io/zh-CN/' },
      { id: 24, text: 'Vue Multiselect', introduction: 'Vue.js 的通用选择/多选/标记组件', url: 'https://vue-multiselect.js.org/' },
      { id: 26, text: 'Vue I18n', introduction: 'Vue3的国际化插件', url: 'https://vue-i18n.intlify.dev/' },
      { id: 27, text: 'Vue Cropper', introduction: '简单的vue图片裁剪插件', url: 'http://github.xyxiao.cn/vue-cropper/example/' },
      { id: 28, text: 'Vue Qrcode Reader', introduction: '允许在不离开浏览器的情况下检测和解码二维码', url: 'https://gruhn.github.io/vue-qrcode-reader/' },
      { id: 29, text: 'Better Scroll', introduction: '解决移动端/PC 各种滚动场景需求的插件。', url: 'https://better-scroll.github.io/docs/zh-CN/' },
      { id: 30, text: 'Vue Press', introduction: 'Vue 驱动的静态网站生成器', url: 'https://v2.vuepress.vuejs.org/zh/' },
      { id: 31, text: 'Calendar', introduction: '获取中国农历公历转化(万年历Web组件)', url: 'https://passer-by.com/calendar/' },
      { id: 45, text: 'Calendar', introduction: '日历组件', url: 'https://fullcalendar.io/' },
      { id: 32, text: 'LuckyCanvas', introduction: '小程序/vue/react/uni抽奖插件', url: 'https://github.com/buuing/lucky-canvas' },
      { id: 33, text: 'Antv', introduction: 'X6 图编辑引擎', url: 'https://x6.antv.antgroup.com/' },
      { id: 34, text: 'NPM', introduction: 'npm依赖查询', url: 'https://www.npmjs.com/' },
      { id: 35, text: 'UIverse', introduction: '适用于任何项目的开源 UI 元素/动画', url: 'https://uiverse.io/' },
      { id: 36, text: 'Driver.Js', introduction: '前端页面引导插件', url: 'https://driverjs.com/' },
      { id: 37, text: 'HiPrint', introduction: '免费、简单、快速的JS打印插件', url: 'http://hiprint.io/' },
      { id: 38, text: 'vue-plugin-hiprint', introduction: '免费、简单、快速的JS打印插件-2', url: 'https://gitee.com/CcSimple/vue-plugin-hiprint#https://ccsimple.gitee.io/vue-plugin-hiprint/' },
      { id: 39, text: 'coolui-scroller', introduction: '一个专注小程序下拉的组件库', url: 'https://harbin_kuchuang_network_wz666s.gitee.io/coolui-scroller/v3/' },
      { id: 40, text: 'wangeditor', introduction: '开源 Web 富文本编辑器，开箱即用，配置简单', url: 'https://www.wangeditor.com/' },
      { id: 41, text: 'vue-particles', introduction: '动态背景插件', url: 'https://vue-particles.netlify.app/' },
      { id: 42, text: 'vue-Telephone', introduction: 'Vue 输入国际电话插件', url: 'https://vue-tel-input.iamstevendao.com/' },
      { id: 43, text: 'wicky', introduction: '不依赖任何框架的一个小型日历库', url: 'https://wicky.nillia.ms/cally/' },
      { id: 44, text: 'PDF 生成库', introduction: '用于 Node 和浏览器的 JavaScript PDF 生成库', url: 'https://github.com/foliojs/pdfkit' },
      { id: 45, text: 'vueflow', introduction: 'VUE流程图', url: 'https://vueflow.dev/' },
      { id: 45, text: 'Y.js', introduction: '协同编辑', url: 'https://yjs.dev/' },
      { id: 45, text: 'Wavesurfer.js', introduction: '开源音频可视化库', url: 'https://wavesurfer.xyz/' },
      { id: 45, text: 'Danmaku', introduction: '强大可扩展的弹幕库', url: 'https://imtaotao.github.io/danmu/document/zh/' },
      { id: 45, text: 'leafletjs官方文档', introduction: '适用于移动设备的交互式地图的开源库', url: 'https://leafletjs.com/index.html' },
      { id: 45, text: 'leafletjs中文文档', introduction: '适用于移动设备的交互式地图的开源库(中文)', url: 'https://leafletjs.cn/' },
      { id: 45, text: 'Leaflet.TrackPlayer', introduction: '一个leaflet轨迹回放插件', url: 'https://github.com/weijun-lab/Leaflet.TrackPlayer/blob/master/README.zh-CN.md' },
      { id: 45, text: 'Slidev', introduction: '为开发者打造的演示文稿工具', url: 'https://cn.sli.dev/' },
      { id: 45, text: 'Favicon', introduction: '轻松查找、提取和使用网站图标', url: 'https://favicon.run/' },
      { id: 45, text: 'postcss', introduction: '将px单位转换为视口单位', url: 'https://github.com/evrone/postcss-px-to-viewport/blob/HEAD/README_CN.md' },
      { id: 45, text: 'unsplash', introduction: '360全景高清图片下载', url: 'https://unsplash.com/s/photos/panorama' },
      { id: 45, text: 'autofit', introduction: '迄今为止最易用的自适应工具', url: 'https://auto-plugin.github.io/autofit.js/' },
      { id: 45, text: 'GoCaptcha', introduction: '行为验证码', url: 'http://gocaptcha.wencodes.com/' },
      { id: 45, text: 'particles', introduction: 'vue3ts粒子特效插件', url: 'https://particles.js.org/' },
      { id: 45, text: 'vue-starport', introduction: 'Vue 跨路由组件共享效果', url: 'https://github.com/antfu/vue-starport/blob/main/README.zh-Hans.md' },
      { id: 45, text: 'vue-pdf-embed', introduction: 'vue3pdf查看器', url: 'https://github.com/hrynko/vue-pdf-embed' },
      { id: 45, text: 'StPageFlip', introduction: 'js实现翻书效果插件', url: 'https://nodlik.github.io/StPageFlip/' },
      { id: 45, text: 'snapDOM', introduction: '元素截图工具', url: 'https://github.com/zumerlab/snapdom/blob/main/README_CN.md' },
      { id: 45, text: 'tianditu', introduction: '天地图 vue 组件库', url: 'https://soullyoko.github.io/vue-tianditu/' },
    ],
  },
  iconFont: {
    text: '字体图标库',
    isExpand: false,
    items: [
      { id: 1, text: 'Iconfont', introduction: '阿里巴巴矢量图标库', url: 'https://www.iconfont.cn/' },
      { id: 3, text: 'Iconbrew', introduction: 'IconBrew-免费在线开源图标库 SVG', url: 'https://iconbrew.com/' },
      { id: 4, text: 'Yesicon', introduction: '157 组开源、免费的图标库', url: 'https://yesicon.app/' },
      { id: 2, text: '700 + CSS Icons', introduction: '纯css的icons', url: 'https://css.gg/' },
      { id: 2, text: 'Iconpark', introduction: '字节跳动出品，将一个SVG图标转化为多个主题', url: 'https://iconpark.oceanengine.com/home' },
    ],
  },
  interview: {
    text: '前端 - 复习/面试题',
    isExpand: false,
    items: [
      { id: 1, text: 'WebInterview', introduction: 'web前端超全面试题大全', url: 'https://interview2.poetries.top/' },
      { id: 2, text: 'WebInterview2', introduction: 'web前端超全面试题大全2', url: 'https://vue3js.cn/interview/' },
      { id: 3, text: 'WebInterview3', introduction: 'web前端超全面复习笔记', url: 'https://github.com/CavsZhouyou/Front-End-Interview-Notebook' },
    ],
  },
  ai: {
    text: '人工智能 - (部分网站访问需科学上网)',
    isExpand: false,
    items: [
      { id: 1, text: 'chat GPT', introduction: 'chat GPT官方', url: 'https://chat.openai.com/' },
      { id: 2, text: 'theb chat', introduction: 'theb chat/收费', url: 'https://beta.theb.ai/home' },
      { id: 3, text: 'ali Chat-GPT', introduction: '通义万相', url: 'https://wanxiang.aliyun.com/' },
      { id: 4, text: 'xfyun Chat-GPT', introduction: '讯飞星火', url: 'https://xinghuo.xfyun.cn/desk' },
      { id: 5, text: 'baidu Chat-GPT', introduction: '文心一言', url: 'https://yiyan.baidu.com/' },
      { id: 6, text: 'Chat-PPT', introduction: '一键生成对话ppt', url: 'https://chat-ppt.com/' },
      { id: 7, text: 'Builder', introduction: '日报周报生成器', url: 'https://weeklyreport.avemaria.fun/zh' },
      { id: 8, text: 'Doubao', introduction: '字节跳动Chat GPT', url: 'https://www.doubao.com/' },
      { id: 9, text: 'chat Mistral', introduction: 'mistral Chat GPT', url: 'https://chat.mistral.ai/chat' },
      { id: 10, text: 'Gemini', introduction: '谷歌 Gemini', url: 'https://gemini.google.com/' },
      { id: 11, text: 'kimi', introduction: '月之暗面AI', url: 'https://kimi.moonshot.cn/chat/empty' },
      { id: 12, text: 'DeepSeek', introduction: 'DeepSeek', url: 'https://chat.deepseek.com/' },
      { id: 13, text: 'Claude', introduction: 'Claude', url: 'https://www.anthropic.com/' },
      { id: 14, text: 'perplexity', introduction: 'perplexity-大数据模型', url: 'https://www.perplexity.ai/' },
      { id: 15, text: 'same', introduction: '可以cv网站的大模型', url: 'https://same.new/' },
      { id: 16, text: 'bolt', introduction: '可以cv网站的大模型-1', url: 'https://bolt.new/' },
      { id: 17, text: 'Readdy', introduction: '可以cv网站的大模型-2', url: 'https://readdy.ai/home/b04cfb3c-8568-4042-8f88-6458b19ea441' },
      { id: 18, text: 'fluxBahew', introduction: '免费在线照片艺术化处理', url: 'https://flux.bahew.com/zh-CN' },
    ],
  },
  learningRoute: {
    text: '其他工具 - (部分网站访问需科学上网)',
    isExpand: false,
    items: [
      { id: 1, text: 'learningRoute', introduction: '开发者学习路线图', url: 'https://roadmap.sh/roadmaps' },
      { id: 4, text: 'Excalidraw', introduction: 'Excalidraw在线画图工具', url: 'https://excalidraw.com/' },
      { id: 5, text: 'V2Club', introduction: '科学上网工具', url: 'https://my.v2fly.club/#/dashboard' },
      { id: 6, text: 'Mojie', introduction: '科学上网工具-2', url: 'https://www.mojie.me/#/login' },
      { id: 6, text: 'Mojie', introduction: '科学上网工具-3', url: 'https://ecycloud.me/#/dashboard' },
      { id: 19, text: 'Mac', introduction: 'mac软件免费下载', url: 'https://macwk.cn/#term-47' },
      { id: 7, text: 'Mac', introduction: 'mac软件免费下载-2', url: 'https://appstorrent.ru/programs/' },
      { id: 7, text: 'Mac', introduction: 'mac软件免费下载-3', url: 'https://www.macw.com/' },
      { id: 8, text: 'Music', introduction: '音乐免费下载', url: 'https://music.liuzhijin.cn/' },
      { id: 9, text: 'MD', introduction: '马克飞象MD文档在线编写教程', url: 'https://maxiang.io/' },
      { id: 10, text: 'Tinypng', introduction: '熊猫图片压缩', url: 'https://tinypng.com/' },
      { id: 26, text: 'Tinypng', introduction: '迅捷图片压缩', url: 'https://yasuo.xunjiepdf.com/img/' },
      { id: 11, text: 'Mdn', introduction: '开发人员资源', url: 'https://developer.mozilla.org/zh-CN/' },
      { id: 12, text: 'Ipinfo', introduction: '本机代理ip查询', url: 'https://ipinfo.io/' },
      { id: 14, text: 'Ahhhhhfs', introduction: '全能网站', url: 'https://www.ahhhhfs.com/' },
      { id: 15, text: 'ImageTool', introduction: '多功能图片转换器', url: 'https://imagestool.com/webp2jpg-online/' },
      { id: 17, text: 'Magiconch', introduction: '神奇海螺试验场', url: 'https://lab.magiconch.com/' },
      { id: 18, text: 'Befunky', introduction: '图片滤镜修改', url: 'https://www.befunky.com/create/photo-to-cartoon/' },
      { id: 19, text: 'dev', introduction: '前端工具类', url: 'https://sinqi.tools/zh' },
      { id: 19, text: 'dev', introduction: '前端工具类-1', url: 'https://hu-snail.github.io/vue3-resource/' },
      { id: 13, text: 'Twitter', introduction: 'Twitter网页版', url: 'https://twitter.com/home?newtwitter=true' },
      { id: 14, text: 'Tiktok', introduction: 'Tiktok网页版', url: 'https://www.tiktok.com/foryou' },
      { id: 15, text: 'Ps', introduction: '在线ps', url: 'https://www.tuyitu.com/ps/sources/' },
      { id: 16, text: 'MoFang', introduction: '魔方简历', url: 'https://magicv.art/zh' },
      { id: 17, text: 'linuxDo', introduction: 'linux社区', url: 'https://linux.do/' },
      { id: 18, text: 'ncat22', introduction: '网飞猫影视网站', url: 'https://www.ncat22.com/' },
      { id: 18, text: 'moovie', introduction: '影视网站', url: 'https://moovie.c2v2.com/' },
      { id: 18, text: 'x video downloader', introduction: 'x视频下载', url: 'https://x-twitter-downloader.com/' },
      { id: 18, text: 'convertio', introduction: '文件转换器', url: 'https://convertio.co/zh/' },
    ],
  },
  website: {
    text: '其他收藏网站',
    isExpand: false,
    items: [
      { id: 1, text: '', introduction: '移动端强制横屏显示', url: 'https://www.cnblogs.com/cy3664983/p/9101542.html' },
      { id: 2, text: '', introduction: '微信小程序form验证', url: 'https://github.com/wux-weapp/wx-extend/blob/master/src/assets/plugins/wx-validate/WxValidate.js' },
      { id: 3, text: '', introduction: 'Vue+高德地图巡航轨迹，实现轨迹回放加进度条，加减速', url: 'https://www.cnblogs.com/Deters/p/13385137.html' },
      { id: 4, text: '', introduction: 'Vue2.0+ 利用高德地图的巡航轨迹， 做带进度条和倍速的轨迹回放', url: 'https://blog.csdn.net/js_admin/article/details/108823205' },
      { id: 5, text: '', introduction: '高德a-map/高德地图2.0版本的vue3对应封装', url: 'https://vue-amap.guyixi.cn/' },
      { id: 6, text: '', introduction: '高德a-map/基于 Vue 2.x 与高德的地图组件', url: 'https://docs.guyixi.cn/vue-amap/#/' },
      { id: 7, text: '', introduction: '在Vue中使用Vant组件-picker选择器，并给选择器添加搜索功能', url: 'https://blog.csdn.net/weixin_43906233/article/details/125943267' },
      { id: 8, text: '', introduction: '巧用 transition 实现短视频 APP 点赞动画', url: 'https://juejin.cn/post/7137488981519761416' },
      { id: 9, text: '', introduction: '解决el-select数据量过大的3种方法', url: 'https://juejin.cn/post/7278238985448341544' },
      { id: 10, text: '', introduction: '移动端适配解决方案', url: 'https://juejin.cn/post/7057156620320505863' },
      { id: 11, text: '', introduction: '移动端适配解决方案-2', url: 'https://juejin.cn/post/7223641276850733113' },
      { id: 12, text: '', introduction: 'vben admin开源的后台管理系统', url: 'https://doc.vvbin.cn/' },
      { id: 13, text: '', introduction: 'Jsplumb基础教程-基于Vue3的流程连线解决方案', url: 'https://blog.csdn.net/weixin_39085822/article/details/106879459' },
      { id: 14, text: '', introduction: 'Jsplumb中文基础教程', url: 'https://wdd.js.org/jsplumb-chinese-tutorial/#/' },
      {
        id: 15,
        text: '',
        introduction: 'el-iamge/无图终极解决办法',
        url: 'https://blog.csdn.net/weixin_46711427/article/details/124595716?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522170607968116800186529357%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=170607968116800186529357&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~baidu_landing_v2~default-4-124595716-null-null.142^v99^pc_search_result_base7&utm_term=ElImageViewer&spm=1018.2226.3001.4187',
      },
      { id: 16, text: '', introduction: 'uniapp连接商米手持机打印机插件', url: 'https://blog.csdn.net/weixin_56478633/article/details/135054900' },
      { id: 17, text: '', introduction: '生成uniapp启动图-storyboard文件', url: 'https://www.chuxueyun.com/#/pages/Launch' },
    ],
  },
});
export { newToolItems };
